environment          = "prod"
app_url              = "https://www.cogletta.com"
contact_email        = "read@cogletta.com"
app_name             = "Cogletta"
ses_from_email       = "read@cogletta.com"
cors_origin          = "https://cogletta.com,https://www.cogletta.com"
cors_allowed_origins = ["https://www.cogletta.com","https://cogletta.com" ]
domain_name          = "cogletta.com"
domain_aliases       = ["cogletta.com", "www.cogletta.com"]
